
namespace:
  name: staging

service:
  port: 5111

replicaCount: 3

resources:
  requests:
    memory: 90Mi
    cpu: 300m
  limits:    # same as default but repeated to conform to spec 
    memory: 128Mi
    cpu: 500m

